spring:
  profiles:
    active: 
    - dev

---
spring:
     profiles: dev
     port: 3366
     application:
       name: ms-cloud-config-dev

---
spring:
  profiles: test
  port: 3355
  application:
    name: ms-cloud-config-test
